# Generated by Django 2.0.7 on 2018-07-10 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelephoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default=None, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "9999999999". The first two digits are the area code. The phone number is composed of 8 or 9 digits.', regex='^\\+?1?\\d{10,11}$')])),
            ],
        ),
    ]
