# Generated by Django 2.0.7 on 2018-07-10 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecall',
            name='destination',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_number', to='telephone_numbers.TelephoneNumber'),
        ),
        migrations.AlterField(
            model_name='phonecall',
            name='source',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_number', to='telephone_numbers.TelephoneNumber'),
        ),
    ]
