# Generated by Django 2.0.7 on 2018-07-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_auto_20180711_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecall',
            name='type',
            field=models.CharField(choices=[('START', 'start'), ('END', 'end')], max_length=5),
        ),
    ]
