# Generated by Django 2.0.7 on 2018-07-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0005_auto_20180713_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecall',
            name='type',
            field=models.CharField(choices=[('start', 'start'), ('end', 'end')], max_length=5),
        ),
    ]
